version: '3.4'

services:
  burgershop.api:
    image: burgershop.api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "burgershop.data"
  burgershop.data:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "burger"
      POSTGRES_PASSWORD: "burger"
      POSTGRES_DB: "burgerShopDb"

  rabbitmq:
    image: masstransit/rabbitmq
    environment:
      - "5672:5672"
      - "15672:15672"